# Do not edit. Generated by the configure script.
export PATH:=/home/pi/kompilacija/node-v14.15.4/out/tools/bin:$(PATH)
BUILDTYPE=Release
NODE_TARGET_TYPE=executable
PYTHON=/usr/bin/python3.7
PREFIX=/usr/local
